/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasBackground: typeof import('./src/components/CanvasBackground/index.vue')['default']
    CommonButton: typeof import('@vunio/ui')['CommonButton']
    CommonDialog: typeof import('@vunio/ui')['CommonDialog']
    CommonForm: typeof import('@vunio/ui')['CommonForm']
    CommonSelect: typeof import('@vunio/ui')['CommonSelect']
    CommonTable: typeof import('@vunio/ui')['CommonTable']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    MonacoEditor: typeof import('./src/components/MonacoEditor/index.vue')['default']
    RollingNumber: typeof import('./src/components/RollingNumber/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenNode: typeof import('./src/components/ScreenRenderer/ScreenNode.vue')['default']
    ScreenRenderer: typeof import('./src/components/ScreenRenderer/index.vue')['default']
    ThemeColorPicker: typeof import('./src/components/ThemeColorPicker/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
