import type {
  BusinessSystem,
  DesignProject,
  ProjectPageRecord,
  PublicModuleRecord,
} from './types.ts'

export const businessSystems: BusinessSystem[] = [
  {
    id: 'production',
    name: '生产运营',
    description: '生产态势、能源与质量运营大屏',
    icon: 'fluent:production-20-regular',
  },
  {
    id: 'park',
    name: '智慧园区',
    description: '园区安防、空间与通行管理',
    icon: 'fluent:building-multiple-20-regular',
  },
  {
    id: 'equipment',
    name: '设备中心',
    description: '设备运行、巡检与预测维护',
    icon: 'fluent:settings-cog-multiple-20-regular',
  },
]

export const projectPages: ProjectPageRecord[] = [
  {
    id: 'production-overview',
    projectId: 'factory-command',
    name: '生产运营总览',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 3,
    updatedAt: '今天 14:32',
    thumbnailVariant: 'operations',
  },
  {
    id: 'shift-analysis',
    projectId: 'factory-command',
    name: '班组效能分析',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 2,
    updatedAt: '昨天 18:06',
    thumbnailVariant: 'equipment',
  },
  {
    id: 'quality-trace',
    projectId: 'factory-command',
    name: '质量追溯中心',
    width: 2560,
    height: 1440,
    moduleReferenceCount: 1,
    updatedAt: '07-25 09:18',
    thumbnailVariant: 'logistics',
  },
  {
    id: 'energy-dashboard',
    projectId: 'energy-insight',
    name: '综合能耗看板',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 2,
    updatedAt: '今天 11:20',
    thumbnailVariant: 'energy',
  },
  {
    id: 'carbon-map',
    projectId: 'energy-insight',
    name: '碳排放分布',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 1,
    updatedAt: '07-24 16:40',
    thumbnailVariant: 'overview',
  },
  {
    id: 'warehouse-flow',
    projectId: 'supply-chain',
    name: '仓储物流态势',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 2,
    updatedAt: '07-23 10:08',
    thumbnailVariant: 'logistics',
  },
  {
    id: 'park-overview',
    projectId: 'smart-park',
    name: '园区综合态势',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 3,
    updatedAt: '今天 09:45',
    thumbnailVariant: 'park',
  },
  {
    id: 'security-center',
    projectId: 'smart-park',
    name: '安防联动中心',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 2,
    updatedAt: '昨天 16:22',
    thumbnailVariant: 'operations',
  },
  {
    id: 'equipment-health',
    projectId: 'equipment-health',
    name: '设备健康总览',
    width: 1920,
    height: 1080,
    moduleReferenceCount: 2,
    updatedAt: '今天 13:10',
    thumbnailVariant: 'equipment',
  },
]

export const publicModules: PublicModuleRecord[] = [
  {
    id: 'module-kpi-strip',
    projectId: 'factory-command',
    name: '核心指标条',
    version: 'v3',
    referenceCount: 2,
    updatedAt: '今天 13:58',
    thumbnailVariant: 'operations',
    exposedParameters: ['标题', '显示数量', '指标口径'],
  },
  {
    id: 'module-alarm-feed',
    projectId: 'factory-command',
    name: '实时告警播报',
    version: 'v2',
    referenceCount: 3,
    updatedAt: '07-26 17:30',
    thumbnailVariant: 'equipment',
    exposedParameters: ['标题', '显示数量', '告警等级'],
  },
  {
    id: 'module-shift-card',
    projectId: 'factory-command',
    name: '班组状态卡',
    version: 'v5',
    referenceCount: 1,
    updatedAt: '07-22 11:08',
    thumbnailVariant: 'logistics',
    exposedParameters: ['班组名称', '状态字段'],
  },
  {
    id: 'module-energy-kpi',
    projectId: 'energy-insight',
    name: '能耗指标组',
    version: 'v2',
    referenceCount: 2,
    updatedAt: '07-24 15:20',
    thumbnailVariant: 'energy',
    exposedParameters: ['标题', '统计周期'],
  },
  {
    id: 'module-park-weather',
    projectId: 'smart-park',
    name: '园区环境卡',
    version: 'v4',
    referenceCount: 2,
    updatedAt: '今天 08:45',
    thumbnailVariant: 'park',
    exposedParameters: ['区域', '显示数量'],
  },
  {
    id: 'module-device-status',
    projectId: 'equipment-health',
    name: '设备状态矩阵',
    version: 'v2',
    referenceCount: 1,
    updatedAt: '今天 12:02',
    thumbnailVariant: 'equipment',
    exposedParameters: ['设备类型', '显示数量'],
  },
]

export const designProjects: DesignProject[] = [
  {
    id: 'factory-command',
    systemId: 'production',
    name: '一号工厂指挥中心',
    description: '聚合产量、质量、设备与班组运行态势',
    updatedAt: '今天 14:32',
    pageIds: ['production-overview', 'shift-analysis', 'quality-trace'],
    moduleIds: ['module-kpi-strip', 'module-alarm-feed', 'module-shift-card'],
    lastEditedPageId: 'production-overview',
    thumbnailVariant: 'operations',
  },
  {
    id: 'energy-insight',
    systemId: 'production',
    name: '能源精益驾驶舱',
    description: '能耗监测、单耗分析与碳排放追踪',
    updatedAt: '今天 11:20',
    pageIds: ['energy-dashboard', 'carbon-map'],
    moduleIds: ['module-energy-kpi'],
    lastEditedPageId: 'energy-dashboard',
    thumbnailVariant: 'energy',
  },
  {
    id: 'supply-chain',
    systemId: 'production',
    name: '供应链协同大屏',
    description: '订单、仓储与运输节点的全程可视化',
    updatedAt: '07-23 10:08',
    pageIds: ['warehouse-flow'],
    moduleIds: [],
    lastEditedPageId: 'warehouse-flow',
    thumbnailVariant: 'logistics',
  },
  {
    id: 'smart-park',
    systemId: 'park',
    name: '滨江智慧园区',
    description: '园区空间、通行、安防与环境综合态势',
    updatedAt: '今天 09:45',
    pageIds: ['park-overview', 'security-center'],
    moduleIds: ['module-park-weather'],
    lastEditedPageId: 'park-overview',
    thumbnailVariant: 'park',
  },
  {
    id: 'visitor-center',
    systemId: 'park',
    name: '访客服务中心',
    description: '访客预约、通行趋势与空间热度',
    updatedAt: '07-20 15:12',
    pageIds: [],
    moduleIds: [],
    lastEditedPageId: '',
    thumbnailVariant: 'overview',
  },
  {
    id: 'equipment-health',
    systemId: 'equipment',
    name: '设备健康管理',
    description: '设备健康评分、故障预测与维护计划',
    updatedAt: '今天 13:10',
    pageIds: ['equipment-health'],
    moduleIds: ['module-device-status'],
    lastEditedPageId: 'equipment-health',
    thumbnailVariant: 'equipment',
  },
]
